version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - apt-get install unzip -y
      - url="https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip"
      - echo $url
      - wget $url
      - unzip terraform*
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - ls
      - echo $STAGE
  build:
    commands:
      - terraform init 
      - terraform workspace select $STAGE || terraform workspace new $STAGE
      - terraform plan -out plan.out
      - terraform apply -lock=true -auto-approve
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - plan.out