version: 0.2

env:
  variables:
    NODE_ENV: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
      # - npm run lint
  pre_build:
    commands:
      - npm i
      - npm run test
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  name: "web-dist-dev"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*