version: 0.2
phases:
  install:
    commands: 
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - mv terraform /bin
      - rm terraform.zip
      - aws sts get-caller-identity
  pre_build:
    commands:
      - ls
      - echo initializing Terraform...
      - terraform init -input=false
  build:
    commands:
      - echo creating terraform plan file...
      - terraform plan -var='key_name=moose' -input=false -out=tfplan
      - echo applying terraform plan
      - terraform apply -lock=true -auto-approve tfplan

  post_build:
    commands:
      - echo "Terraform build succeeded, destroying resources..."
      - terraform destroy -var='key_name=moose' -auto-approve
    
artifacts:
  files: 
    - tfplan